package com.pokework.model;

import java.time.LocalDate;

/**
 * Represents a single work session.
 * This class corresponds to the 'work_sessions' table in the database.
 */
public class WorkSession {
    private int id;
    private LocalDate workDate;
    private double hours;

    // Default constructor (required for some frameworks/serialization)
    public WorkSession() {
    }

    // Constructor for creating new sessions (id is auto-generated by DB)
    public WorkSession(LocalDate workDate, double hours) {
        this.workDate = workDate;
        this.hours = hours;
    }

    // Constructor for reading from DB
    public WorkSession(int id, LocalDate workDate, double hours) {
        this.id = id;
        this.workDate = workDate;
        this.hours = hours;
    }

    // Getters and Setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public LocalDate getWorkDate() {
        return workDate;
    }

    public void setWorkDate(LocalDate workDate) {
        this.workDate = workDate;
    }

    public double getHours() {
        return hours;
    }

    public void setHours(double hours) {
        this.hours = hours;
    }

    @Override
    public String toString() {
        return "WorkSession{" +
                "id=" + id +
                ", workDate=" + workDate +
                ", hours=" + hours +
                '}';
    }
}
